cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3: #버킷이름
      bucket: woosik-bucket
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false
# multipartFile 용량 늘려주는 설정
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  h2 설정
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:springminiprojectdb
    username: sa
    password:
